#
# Copyright (c) 2012-2019 Arne Schwabe
# Distributed under the GNU GPL v2 with additional terms. For full terms see the file doc/LICENSE.txt
#

android.nonTransitiveRClass=false
android.usesSdkInManifest.disallowed=true

# SargO OpenVPN build needs plenty of heap for universal APK + 4 ABI builds.
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=512m
