LOCAL_SRC_FILES_x86 :=
LOCAL_CFLAGS_x86 :=

LOCAL_SRC_FILES_arm64 :=
LOCAL_CFLAGS_arm64 :=

LOCAL_SRC_FILES_arm :=
LOCAL_CFLAGS_arm :=

LOCAL_SRC_FILES_x86_64 :=
LOCAL_CFLAGS_x86_64 :=

LOCAL_SRC_FILES_mips :=
LOCAL_CFLAGS_mips :=
